// Auth Reducer
export const GET_ERRORS = "GET_ERRORS";
export const TOKEN_ERROR = "TOKEN_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PASSWORD_RESET_EMAIL_SENT = "PASSWORD_RESET_EMAIL_SENT";
export const RESET_PASSWORD = "RESET_PASSWORD";

// Profile Reducer
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
